image: woohuiren/laravel-pcf:latest

# Recommended to put into GitLab secret variables instead
variables:
  CF_API_ENDPOINT: woohuiren.me
  CF_USERNAME: woohuiren
  CF_PASSWORD: somepassword
  CF_ORGANIZATION: woohuiren
  CF_SPACE: secret-project
  CF_APP: secret-app-ui

stages:
- build
- test
- staging_deploy

build_job:
  stage: build
  script:
  - sh .gitlab-build.sh
  artifacts:
    paths:
    - vendor/
    - bootstrap/
    - composer.phar
    - .env
  tags:
  - docker

test_job:
  stage: test
  services:
  - mysql:latest
  - redis:latest
  dependencies:
  - build_job
  script:
  - sh .gitlab-test.sh
  tags:
  - docker

stage_job:
  stage: staging_deploy
  dependencies:
  - build_job
  script:
  - cf login -a $CF_API_ENDPOINT -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORGANIZATION -s $CF_SPACE
  - cf check-manifest $CF_APP -f manifest.yml
  - cf blue-green-deploy $CF_APP -f manifest.yml --delete-old-apps
  environment:
    name: staging
